### ISSUE TITLE
Enums are not brought through on the service proxies UI

### ISSUE THREAD

**Issue by afoxsonoco** [IntentArchitect/Support#101]
### What happened?

When using an enum as a query parameter they are not added to the service proxy page and show up as an error.

![image](https://github.com/user-attachments/assets/ca81176c-4a0a-4cab-9b98-5b698663454e)

The factory and code still runs correctly as if there isn't an error.

### What version of Intent Architect are you using?

4.3.2

**Comment by joelsteventurner** [comment]
Hi @afoxsonoco 

You just need to add a package reference to the package which has the Enum modelled in it (most likely your domain package.)
Let me know if this resolves the issue.

**Comment by afoxsonoco** [comment]
It does, thank you.
