### ISSUE TITLE
appsettings.json JwtToken:RefreshTokenExpiryMinutes naming problem

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [IntentArchitect/Support#103]
### What happened?

There is a naming issue between TokenService and appsettings.json. We can set the RefreshTokenExpiry value as minutes according to the appsettings.json file, but TokenService processes the same value as days.

![image](https://github.com/user-attachments/assets/0ca740a8-1d1f-4368-ad32-aee44d40d058)

### What version of Intent Architect are you using?

4.3.4

### Additional information

Project type : Clean architecture .NET
Security : Identity Account Management

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

Thank you very much for taking the time to report this.

We have now updated the `Intent.AspNetCore.Identity.AccountController` module to pre-release version `3.1.6-pre.0` which fixes this issue.

Please don't hesitate to reach out again should you have any further comments or questions.

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

Another update here, after further consideration from our side, we'll be changing this to instead take in a TimeSpan string and we'll be updating the `appsettings.json` field name accordingly.

I will give an update here once this update has been made.

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

We now have version `4.0.0-pre.0` which changes the fields to have be TimeSpan suffixes and values, this has also been mentioned in the release notes:

![image](https://github.com/user-attachments/assets/127f3897-088d-4533-88be-3f3775039212)

**Comment by SarperMUTLUBAY** [comment]
Hi @JonathanLydall,
Thanks for the fast reply and fast fix. I checked now and everything looks good.
