### ISSUE TITLE
Services screen shows incorrect warning for auditable tables

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [IntentArchitect/Support#104]
### What happened?

When I apply the "Basic Auditing" stereotype to a domain I added from the Domain page, the Services screen shows a warning for the "CreatedBy" and "CreatedDate" fields in the CreateCommand section.

![Auditable Create Command Issue](https://github.com/user-attachments/assets/0a5b7c0a-34f3-47e6-9587-a451713811ca)

### What version of Intent Architect are you using?

4.3.4

### Additional information

Project type : Clean architecture .NET
Additional Module : Intent.Entities.BasicAuditing (v1.0.4)

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

Thank you for taking the time to raise this.

This is indeed a bug where it shouldn't show the warning, we have a ticket on our backlog to look at this as soon as we're able. In the meantime, the warning can be ignored as it will not cause any issues.

We apologize for any inconvenience caused.

**Comment by dandrejvv** [comment]
Hi @SarperMUTLUBAY 
We have fixed the issue you raised and is available by updating the `Intent.Modelers.Services.DomainInteractions` module to `2.0.2-pre.3` (include prerelease).
Please let me know if the issue is fixed for you.

**Comment by SarperMUTLUBAY** [comment]
Hi again @dandrejvv 
I just checked it and it looks fine. Thanks for the quick fix.

![image](https://github.com/user-attachments/assets/0eb32d65-1b14-444c-b348-b3670c0bd464)
