### ISSUE TITLE
UserId claim inconsistency between AccountController and CurrentUserService

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [IntentArchitect/Support#105]
### What happened?

AccountController sets user.Id to claims with "ClaimTypes.NameIdentifier" claim type but CurrentUserService tries to fetch UserId from claims with "JtwClaimTypes.Subject" claim type.

![IdentityWithAuditable Issue](https://github.com/user-attachments/assets/8c10a41a-7aaa-4501-8d34-956b954aba5d)

![IdentityWithAuditable Error Message](https://github.com/user-attachments/assets/87a3ce0e-96c2-4f2a-8e38-ea0f74491fff)

### What version of Intent Architect are you using?

4.3.4

### Additional information

Project type : Clean architecture .NET
Security : Identity Account Management
Additional Module : Intent.Entities.BasicAuditing (v1.0.4)

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

We appreciate you taking the time to bring this to our attention, I have logged this as a bug for us to look at as soon as possible.

To workaround this issue in the meantime you can add the following additional lines to `AccountController.cs` at line 383:

```csharp
// IntentIgnore
claims.Add(new Claim(IdentityModel.JwtClaimTypes.Subject, user.Id));
```

Making it look like:

![image](https://github.com/user-attachments/assets/85f91d4f-7c00-4912-9cce-303571280a8b)

We apologize for any inconvenience caused.

**Comment by SarperMUTLUBAY** [comment]
Hi again  @JonathanLydall 
I tried your workaround but it didn't work. When I add your workaround to the AccountController, it adds multiple "sub" claim values ​​to the token claims and the API starts returning an "invalid_token" error.

![image](https://github.com/user-attachments/assets/27002e4a-2211-4ca2-beb7-94193424bd9c)

![image](https://github.com/user-attachments/assets/302cb7ad-90a4-44d6-b326-bc55401f03d5)

**Comment by dandrejvv** [comment]
Hi @SarperMUTLUBAY 
I had a look at this issue and made a fix for the `Intent.AspNetCore.Identity.AccountController` module.
The solution will now ensure that the `sub` claim is now set to the `User ID` and it will still have the `name` claim that contains the account Email.
Please update to version 4.1.0-pre.0 (include prerelease in Manage Modules page) for that module and review the changes during the Software Factory Execution to ensure it aligns with your implementation.
Let me know if this solution works for you.

**Comment by SarperMUTLUBAY** [comment]
Hi @dandrejvv 
The new module update fixed the problem. Everything is fine now.
