### ISSUE TITLE
Services screen shows incorrect warning for soft delete tables

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [IntentArchitect/Support#123]
### What happened?

It is almost same issue with the ticket below. Services screen shows a warning about IsDeleted fields on Create and Update commands but IsDeleted field is managing automatically.

https://github.com/IntentArchitect/Support/issues/104

![image](https://github.com/user-attachments/assets/9f1863a0-9380-4011-9fe1-2bfad238453d)

### What version of Intent Architect are you using?

4.3.9

### Additional information

Issue was here before this version.

**Comment by JonathanLydall** [comment]
Thank you for reporting this @SarperMUTLUBAY, we will check why the fix for #104 doesn't seem to have also been automatically applied here and get back to you.

**Comment by JonathanLydall** [comment]
Hi @SarperMUTLUBAY,

If you update the `Intent.EntityFrameworkCore.SoftDelete` module to version `1.0.4-pre.1` it should resolve this issue.

Please don't hesitate to reach out again with any comments or questions.

**Comment by SarperMUTLUBAY** [comment]
Hi @JonathanLydall,
Thanks for the quick solution. I will check it and let you know.

**Comment by SarperMUTLUBAY** [comment]
I just checked it and it looks fine. Thanks for the quick fix.
