### ISSUE TITLE
Listing use cases for services in sub folders

### ISSUE THREAD

**Issue by Laura-BSC** [IntentArchitect/Support#18]
### Ask a question

We have a module to generate documentation for our use cases and domain entities. One of my projects has the use cases split into folders so the use cases aren't picked up. Is there a way to easily traverse the folder structure and get a list of all use cases?
![2023-05-15 09_29_00-Intent Architect __ BSC Group _ Microsoft Teams](https://github.com/IntentArchitect/Support/assets/57346928/d4c9faf3-bad1-402d-9d4c-61c91ff79c99)

**Comment by JonathanLydall** [comment]
Hi @Laura-BSC,

The same metadata manager that one uses from `TemplateRegistration`s is also accessible in Templates themselves from `OutputTarget.ExecutionContext.MetadataManager` and it can be used to get all models of a type. For example, you could get all the classes from the Domain Designer by going:

```csharp
var classes = OutputTarget.ExecutionContext.MetadataManager
    .Domain(OutputTarget.ExecutionContext.GetApplicationConfig().Id)
    .GetClassModels();
```

You would just need to use the correct extension methods to get your custom `UseCase` element type.

Let me know if you need more detail 🙂.
