### ISSUE TITLE
Documentation on C# File Builder

### ISSUE THREAD

**Issue by Laura-BSC** [IntentArchitect/Support#32]
### Ask a question

Hi team,

Is there any documentation available on using the C# File Builder templating method? If so, please could you share the link. I wasn't able to find it in the documentation.

Thanks

**Comment by dandrejvv** [comment]
Hi @Laura-BSC . Thanks for your question. This is something that we are planning to do very soon. If you have any specific questions around the File Builder, please feel free to reach out in the support channels.

**Comment by dandrejvv** [comment]
Hi @Laura-BSC ,
As fully documenting the entire surface area of this API is going to take us some time, in the meantime we've decided to focus where template authors have specific questions. Towards this, please ask any specific questions you may have as new GitHub issues here and as part of our response we'll also be adding them to particular documentation, in the form of a readme file for the builder or as XML Doc Comments in the C# code as appropriate.
In the meantime, is there any particular information you're looking for?

**Comment by Laura-BSC** [comment]
Nothing specific, I was looking for a general usage guide,
