### ISSUE TITLE
Get Request shouldn't have a payload

### ISSUE THREAD

**Issue by Braydon111** [IntentArchitect/Support#34]
### Ask a question

Hi I generated CQRS CRUD and exposed http GET endpoint. It currently requires a payload rather than a query parameter. How do i switch [FromBody] to [FromRoute]?

**Comment by JonathanLydall** [comment]
Hi @Braydon111,

As HTTP doesn't support payloads for the GET verb, our CRUD script shouldn't be trying to set it up to use the body at all here.

Can you post a screenshot the with the `Query` node expanded in Intent Architect and also post the generated code for the operation?

**Comment by Braydon111** [comment]
Hi Jonathan,

certainly:
![Screenshot 2023-06-19 161504](https://github.com/IntentArchitect/Support/assets/136085096/c898a4e7-4afa-4ad3-9acf-56ce8a5d13bb)

![Screenshot 2023-06-19 161556](https://github.com/IntentArchitect/Support/assets/136085096/12dc5e83-4d3a-4f01-ace8-f24981f5194a)

**Comment by joelsteventurner** [comment]
Hi @Braydon111 

Could I get a screen shot of the SurgeryFormResult entity in your domain ?

**Comment by joelsteventurner** [comment]
Hi @Braydon111 

Thanks for the call to investigate and resolve the issue, that additional FK without an association seems to have been causing issues.

I have logged 2 tickets on our side, one to try prevent this situation in the future and a second to improve how Intent deals with scenarios like this.
