### ISSUE TITLE
Creating Generic Java class

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#35]
### Ask a question

I'm using the new Java Builder Template, to create a new class, but I want to create a Generic Java class... problem is I could not find a proper way (or that I could see) to do this, so I "hacked" it like this, but I would like to know what is the proper way to do this.

  .AddClass($"DroolRuleCompiler", c => { c.WithBaseType("T"); })

and in TransformText:

   return JavaFile.ToString().Replace(" extends T", "<T>");

So is there a way to this without doing the "replace" portion?

**Comment by dandrejvv** [comment]
Good day @leonAtRain,

The JavaFileBuilder does not yet have support for defining Generic types, but as this is something you clearly now need, we can prioritise getting it added in the short term (within the next few weeks).

Although absolutely in no way expected, in the event you would like to update the JavaFileBuilder yourself sooner, we would be happy to provide guidance to you being able to make a pull request with the improvements in the [Intent.Modules](https://github.com/IntentArchitect/Intent.Modules) repository. The FileBuilder itself is over [here](https://github.com/IntentArchitect/Intent.Modules/tree/development/Modules/Intent.Modules.Common.Java/Builder) with unit tests over [here](https://github.com/IntentArchitect/Intent.Modules/blob/development/Modules/Intent.Modules.Common.Java.Tests/Builder/BuilderTests.cs).

**Comment by dandrejvv** [comment]
This feature has been completed as part of this commit [0c463f5](https://github.com/IntentArchitect/Intent.Modules/commit/0c463f581ab13258df894a95c71f7cd8863997af) as I've added support for Generics on a Class and Method level.
