### ISSUE TITLE
Java-File-Builder always add Template to the name of the class

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#37]
### What happened?

When creating new class in Module Builder - the SF always adds an "AddClass" to the template, and also a class with the name "Template" added. For example - on the left is the Properties as they are in IA, and on the right what it adds to the file.
![image](https://github.com/IntentArchitect/Support/assets/129200997/b2c29ee4-749a-459d-9732-632e2b4899ff)

### What version of Intent Architect are you using?

4

**Comment by dandrejvv** [comment]
Hi @leonAtRain.
As it stands if you were to call your template `DroolRuleCompilerTemplate` then it will add that string as-is to the `AddClass` like this `AddClass("DroolRuleCompilerTemplate", ...)`. We can certainly make an enhancement to truncate the `Template` from the class name in that case.

**Comment by dandrejvv** [comment]
Hi @leonAtRain .
Also please check your Template has the `IntentManaged` set to `Merge` which is why it didn't update the ClassName and why its attempting to add more code in the constructor. Change it to `[IntentManaged(Mode.Fully, Body = Mode.Ignore)` to resolve your immediate issue.

**Comment by dandrejvv** [comment]
The `Intent.ModuleBuilder.Java` module (from `3.4.1-pre.0`) has been updated so that adding a new Template that is Single File in nature with a name containing a suffix `Template` will no longer add `Template` as part of the Class name.
