### ISSUE TITLE
"Package could not be found" error creating new module

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#38]
### What happened?

In v4 of Intent, in an existing application (once the application is already open)
- Select "Create new application" plus button (NOT right-click "Create new application" on the solution) 
- Select "Intent Module Builder" (v3.3.26)
- Give a name - leave other settings as default. Click Next
- Check "Module Builder - C#" and change Target Framework to .NET5.0
- Click "Create"

This error occurs:
![image](https://github.com/IntentArchitect/Support/assets/45011398/f90c1a92-41f0-4e58-aec7-dca48b361889)

This error does not occur if using the "Create new application" plus button (another issue occurs then, will log a separate ticket for that).

When creating a new application in v3 of Intent, the error does not occur.

### What version of Intent Architect are you using?

4.0.1

**Comment by joelsteventurner** [comment]
Hi @jpseini 

Looking into the issue there appears to be a file locking problem occurring. I have logged a ticket on our side to investigate and resolve this issue on our side.

As discussed, the current work around, when you want to add a new Module Builder Application to an existing Solution.
1) Close all your designer tabs of the existing Solution.
2) Click on the Intent Icon in the Tool bar (top left), the one which takes you to the Home screen.
3) Close Intent Architect.
4) Re-open the Solution and add / create a new Application using the Module Builder template.

**Comment by jpseini** [comment]
Hi @JonathanLydall  - thanks, initial tests show it is working.
