### ISSUE TITLE
"Intent.VisualStudio.Projects" not accessible during module creation

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#39]
### What happened?

In v4 of Intent, in an existing application (once the application is already open)

- Right-click "Create new application" on the solution (do NOT use the plus button to create new application)
- Select "Intent Module Builder" (v3.3.26)
- Give a name - leave other settings as default. Click Next
- Check "Module Builder - C#" and change Target Framework to .NET5.0
- Click "Create"

The following error occurs:
![image](https://github.com/IntentArchitect/Support/assets/45011398/3321b216-f407-42c8-9f40-4f3a7500cb0b)

The module is (half) created - going into the "Modules" of the new modules and trying to reinstall "Intent.VisualStudio.Projects", I then get the following:
![image](https://github.com/IntentArchitect/Support/assets/45011398/345d6288-bca7-49b2-a45b-c8eb4ff3f42e)

If I close Intent, reopen, and reinstall "Intent.VisualStudio.Projects", the module is installed successfully, and the Visual Studio designer is added to the module, but does not contain any package (and thus has none of the required roles and template outputs added)

Performing the above in v3 of Intent runs without issues.

### What version of Intent Architect are you using?

4.0.1

**Comment by joelsteventurner** [comment]
Hi @jpseini 

This issue is the same underlying problem as #38.  We will make sure both cases work when addressing this issue. Going to close this ticket as it's the same problem.

**Comment by JonathanLydall** [comment]
Hi @jpseini, we have a fix for this issue in `4.0.2-pre.6` if you would like to test it there.
