### ISSUE TITLE
Duplicate Service endpoints

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#45]
### What problem are you trying to solve?

For some odd reason, making duplicate service endpoints are allowed:
![image](https://github.com/IntentArchitect/Support/assets/129200997/3a8ec0c6-ad61-4c5b-8c11-4c218cb0ce55)

### Describe the solution you'd like

Can I ask that a similar feature be added - like adding duplicate DTO's - this theoretically is almost possible, if any of the parameters are different - so that is fine, but in this specific scenario - nothing differs.

**Comment by dandrejvv** [comment]
Hi @leonAtRain .
Good suggestion. Will log it on our backlog and keep you up to date with this improvement.

**Comment by dandrejvv** [comment]
Hi @leonAtRain. 
There is a fix for this now in the module `Intent.Modelers.Services` (version 3.4.7).
Once you update that module it should take effect. Please let me know if this solved your problem.
