### ISSUE TITLE
Generating a CSharpFile from ClassModel

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#47]
### Ask a question

Is there existing functionality in any Intent modules, which is able to take a ClassModel instance (designed in the Domain Designer), and automatically convert it to a CSharpFile (the same as if it was generated using the builder pattern)?
Or is the way to do that conversion up to the builder of the module (me in this instance) to do that mapping and setup of the class using the builder pattern to create an instance of CSharpFile?

**Comment by jpseini** [comment]
@JonathanLydall  - do you have an example of "converting" a ClassModel to a CSharpFile? Just so I can make sure I'm on the right track and doing it correctly?

**Comment by garethbaars** [comment]
Hi @jpseini,

Here's a quick example:
```
CSharpFile = new CSharpFile(this.GetNamespace(), this.GetFolderPath())
    .AddClass($"{Model.Name}", @class =>
    {
        foreach (var attr in Model.Attributes)
        {
            @class.AddProperty(GetTypeName(attr), attr.Name.ToPascalCase());
        }
        foreach (var associations in Model.AssociatedClasses)
        {
            @class.AddProperty(GetTypeName(associations), associations.Name.ToPascalCase());
        }
        foreach (var operation in Model.Operations)
        {
            @class.AddMethod(GetTypeName(operation), operation.Name.ToPascalCase(), method =>
            {
                foreach (var parameter in operation.Parameters)
                {
                    method.AddParameter(GetTypeName(parameter), parameter.Name.ToCamelCase());
                }
            });
        }
    });
```
If the model is as follows:
![image](https://github.com/IntentArchitect/Support/assets/11704575/e0700f3a-cddf-4b55-997d-69c93cde2f4a)

This would output the following code:
![image](https://github.com/IntentArchitect/Support/assets/11704575/6977988b-2eb2-43b4-8000-aa810d321905)

Does this give you what you are looking for?

**Comment by jpseini** [comment]
Perfect - thanks @JonathanLydall
