### ISSUE TITLE
Parameter comments in method XML documentation

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#49]
### Ask a question

Related to #47 - when generating c# code from a ClassModel created in the Domain Designer, is there a way to add operation parameter comments to the operation XML documentation?

I am adding XML comments using:
``` csharp
method.TryAddXmlDocComments(operation.InternalElement);
```
which adds the operation comments correctly and successfully, but not any operation parameter comments

Designer:
![image](https://github.com/IntentArchitect/Support/assets/45011398/59c99c1b-6cd2-4a6f-97fd-8f5c2a307a2e)

Generated code:
![image](https://github.com/IntentArchitect/Support/assets/45011398/107d7671-9323-442f-98b7-73bf09ad9551)

1. Is there currently a way to achieve this? 
1. If not, is there a suggested way to handle Intent ignore any XML documentation comments added by the user (if for example, Intent generated only the class structure, and the user documented it manually)

Thanks.

**Comment by joelsteventurner** [comment]
Hi @jpseini 

I've logged this as an improvement on our product backlog. I'll keep you posted on when  this is available.
 
As for getting Intent to Ignore Comments you can do something like this.

![image](https://github.com/IntentArchitect/Support/assets/11704606/390f6112-818f-45ec-90c4-f991e8638630)

Hopefully this helps you out for now, if not let me know and I'll see what else I can do.

**Comment by jpseini** [comment]
Thanks @joelsteventurner. The code snippet above will definitely work for me for now - thanks for it.

**Comment by joelsteventurner** [comment]
Hi @jpseini 

Just to let you know we have a pre-release out with this feature, i.e. Operation parameter comments added to the XmlDocComments. You would need to update the following modules.

Intent.Common.CSharp - v3.3.39-pre.4
Intent.Application.Contracts - v5.0.2-pre.0
Intent.Application.ServiceImplementations - 4.3.1-pre.0

Let me know if you have any questions or issues.
