### ISSUE TITLE
"Failed to set up execution environment" error when running the Software Factory

### ISSUE THREAD

**Issue by fdbkersten** [IntentArchitect/Support#50]
### What happened?

![image](https://github.com/IntentArchitect/Support/assets/115829322/22faf29d-294e-4cb0-ac05-41a13acd9e57)

### What version of Intent Architect are you using?

4.0.2

### Additional information

This started happening from today for me

**Comment by joelsteventurner** [comment]
Hi @fdbkersten 

We will have to investigate and try get to the bottom of what's going on there.  Just a couple quick questions my side,
* It sounds like you've had this more than once - how frequently is this happening and its there "common theme" to what your are doing when it happens?
* you mentioned this started today - anything which happened today which may have contributed ?

In the meantime, I'll try start with that trace but any additional info would be appreciated.

**Comment by JonathanLydall** [comment]
Hi @fdbkersten,

By any chance was this instance of Intent Architect opened by double-clicking a `.isln` file? If so, can you try close Intent and start it up from your Start menu directly and see if it resolves the issue?

**Comment by JonathanLydall** [comment]
Hi @fdbkersten,

We've now worked out how to reliably reproduce this issue and will be fixing it as soon as possible.

When you open Intent Architect by opening a particular `.isln` file through Windows Explorer, if you try running the software factory for an application in a different solution to the one originally opened, then this error occurs.

So the workaround for now is to restart Intent Architect just through the Start Menu and not for a particular `.isln` file.

Apologies for any inconvenience caused.

**Comment by Magicza** [comment]
Perfect thanks for the feedback

**Comment by JonathanLydall** [comment]
Hi @Magicza,

This is fixed for the upcoming `4.1.0` version of Intent.

**Comment by JonathanLydall** [comment]
@Magicza, this fix has now been made available in `4.0.3-pre.5` if you want to install the latest pre-release, alternatively you can wait for the final `4.0.3` release.
