### ISSUE TITLE
CSharpProject - Worker SDK

### ISSUE THREAD

**Issue by Magicza** [IntentArchitect/Support#52]
### What problem are you trying to solve?

The new project template (with SDK selection) works great (thanks for following through with the request).   

Currently the sdk list does not support the `Worker` SDK. As a result  my SDK hack is still required to handle these hosts.

### Describe the solution you'd like

Add the `Worker` SDK to the selection list

**Comment by JonathanLydall** [comment]
Hi @Magicza,

We appreciate you taking the time to log this issue. `Intent.VisualStudio.Projects` version `3.3.29-pre.0` is now available and has all the SDKs as per https://learn.microsoft.com/dotnet/core/project-sdk/overview#available-sdks including `Microsoft.NET.Sdk.Worker`.

Please don't hesitate to reach out should you have any further questions or requests.
