### ISSUE TITLE
How to action warning received on running SF on .NET solution that uses Directory.Build.props

### ISSUE THREAD

**Issue by chivandikwa** [IntentArchitect/Support#55]
### Ask a question

Please assist with the warning received on running the Software Factory on a .NET solution that uses a Directory.Build.props files, specifically for the target framework. The error is phrased as

> Could not determine framework element for project "x.csproj". If you're using a "Directory.Build.props" file, change the project's Target Framework to "(unspecified)".

I am not sure how this is meant to be actioned as making the TargetFramework in the csproj "(unspecified)" would not be valid.

**Comment by JonathanLydall** [comment]
Hi @chivandikwa,

This warning is saying that it couldn't find a `<TargetFramework />` nor a `<TargetFrameworks />` element in the `.csproj`. In most cases this is because a [`Directory.Build.props` file](https://learn.microsoft.com/visualstudio/msbuild/customize-by-directory) is being used.

Before we propose a possible solution, are you using a `Directory.Build.props` file in this case, or is there something else going on?

**Comment by chivandikwa** [comment]
@JonathanLydall Yes, in this case I am using a Directory.Build.props file that sets the TargetFramework solution wide

**Comment by JonathanLydall** [comment]
Thanks @chivandikwa,

I suspected as much, what we'll be doing is changing our module to not output a warning here anymore.

At one point our advice was to change a setting for the project in the Visual Studio designer for such scenarios, but that's no longer good practice for other reasons, hence us going to instead remove the warning instead.

We'll let you know when the update to the module is ready.

**Comment by JonathanLydall** [comment]
Just to close the loop here for now. We have removed this warning to prevent it getting in the way at all if a `Directory.Build.props` file is used and have a task on our backlog to add more explicit `Directory.Build.props` support at some point in the future.

You can watch our monthly "What's new" emails for when this work has been completed and in the meantime we're closing this issue, but please don't hesitate to add further comments or queries should you have any.
