### ISSUE TITLE
Setting a module supportedClientVersions value

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#56]
### Ask a question

Is there a way in Intent to set the "supportedClientVersions" value for a module? I can't seem to find the option anywhere in the UI.

Otherwise, is the recommended way to just update the value directly in the imodspec file?

Thanks.

**Comment by joelsteventurner** [comment]
Hi @jpseini 

You are correct, this is currently not available in the UI, but you can simply update it in the `imodspec` file.
Here is an example of what this would look like.

![image](https://github.com/IntentArchitect/Support/assets/11704606/0914fc90-e2a9-4760-bc4d-34cb290b0e23)

**Comment by jpseini** [comment]
Perfect, thanks @joelsteventurner.
