### ISSUE TITLE
CSharpFileBuilder - Enum

### ISSUE THREAD

**Issue by fdbkersten** [IntentArchitect/Support#58]
### Ask a question

Hi

After doing some digging I have not been able to find out if it is possible to template an enum using the new CSharpFileBuilder.

Is this possible?
If so, how?
If not, is this planned?

**Comment by dandrejvv** [comment]
Hi @fdbkersten.
We don't have an Enum Builder yet.
I will add a ticket to our backlog to make an Enum builder and will keep you informed.

**Comment by Magicza** [comment]
Thanks. Appreciate it

**Comment by dandrejvv** [comment]
Hi @fdbkersten .
We have created an Enum Builder and is available as pre-release (remember to check the "Include Pre-release" check-box in Intent) if you don't want to wait for the final release.

You will need to update both the Intent Architect module as well as the referenced nuget package.
Module: Intent.Common.CSharp (3.3.40-pre.2)
Nuget: Intent.Modules.Common.CSharp (3.3.40-pre.2)

If you have any further questions, don't hesitate to reach out.

**Comment by dandrejvv** [comment]
Hi @Magicza / @fdbkersten .
We've released a final version of the Module and Nuget package that contains the Enum Builder.
Please make sure you update the `module` `Intent.Common.CSharp` and the `nuget` package `Intent.Modules.Common.CSharp` to `3.3.40`.
