### ISSUE TITLE
JavaDependency - Type requirement

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#60]
### What happened?

Adding JavaDependency in a Template requires sometimes that the type be specified as sell, for example:

```xml
<dependency>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protoc</artifactId>
  <version>${protoc.version}</version>
  **<type>pom</type>**
</dependency>
```

I only see the "Optional" tag that can be set - would it be possible to add the type as well. There are other options that might be useful later as well, but I've not came across them all yet, although I do have use for "scope" and "exclusions" - never used any of the others.
![image](https://github.com/IntentArchitect/Support/assets/129200997/5b168e4f-f4e3-4add-b37d-821a16cef6bf)

### What version of Intent Architect are you using?

4

**Comment by dandrejvv** [comment]
Hi @leonAtRain 
We can certainly look at these capabilities. Will add it in our backlog to assess and will inform you of any updates.
