### ISSUE TITLE
Using Type that does not exist

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#61]
### Ask a question

I have a grpc autogenerated type that I use in my code, called ReferenceDto, but when I specify it in the Services side, I'm not sure how I can use that class, as it does not exist anywhere until the project is built, so now everytime I run SF, this happens:
![image](https://github.com/IntentArchitect/Support/assets/129200997/c5254c94-d0d3-4f9e-9966-9aab67b6e98d)

Is there an easy solution to this?

**Comment by joelsteventurner** [comment]
Hi @leonAtRain 

To achieve this, you can simply add a new type to your designer, using the "Add Type" context menu option on the package.

- Name it "ReferenceDto"
- Apply a Java Strereotype to the newly added type.
- On the Java sterrotype configure the package to "network.rain..."

Now using this type as your operation return type.

**Comment by leonAtRain** [comment]
Hi,
This worked for me, thanks for the quick response.
