### ISSUE TITLE
Intent.VisualStudio.Projects 3.3.30 "IISExpress" error

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#63]
### What happened?

When upgrading an application to use Intent.VisualStudio.Projects version 3.3.30, the follow exception occurs:

![image](https://github.com/IntentArchitect/Support/assets/45011398/efdc1f38-f2a5-42ac-9a1c-52bf18b66d5d)

When downgrading the referenced Intent.VisualStudio.Projects version to 3.3.29, there is no error and the SF runs without issue.

### What version of Intent Architect are you using?

4.0.4

**Comment by joelsteventurner** [comment]
Hi @jpseini 

Thanks for raising this, I have logged the issue our side and will get back to you as soon as we have a patch out for this.

**Comment by JonathanLydall** [comment]
Hi @jpseini,

We expect to have a fix out for the module in the very short term, apologies for any inconvenience caused.

Part of the work in a recent update to the module was leveraging the published schema for `launchsettings.json` file to be able to work with it in a more type-safe way, evidently this also unintentionally introducing case-sensitivity in certain places.

**Comment by joelsteventurner** [comment]
Hi @jpseini 

We have a pre-release out which should address this issue, it's available in:

Intent.VisualStudio.Projects v3.3.31-pre.0 

Please let me know if you need any additional assistance around this issue.

**Comment by jpseini** [comment]
Thanks @joelsteventurner  - I have tested and can confirm that Intent.VisualStudio.Projects v3.3.31-pre.0 appears to fix the issue.
