### ISSUE TITLE
Issue with custom stereotype not being applied

### ISSUE THREAD

**Issue by Laura-BSC** [IntentArchitect/Support#66]
### Ask a question

I have created a custom module. In the module builder, I have defined a custom elements for the domain designer (Security Role & Security Function). I have added stereotype definitions (SecurityRoleData and SecurityFunctionData) that are always applied to elements of the type 'Security Role' and 'Security Function' respectively. Within the same Intent solution, I have created a test app and when I install the module and add the Security Role or Function to the domain, it adds the stereotype as expected.

I am not trying to use the module in another application. I have installed the same version of the module but the stereotype is not applied, nor can it be manually applied.

 Any ideas about what I might have missed?

**Module builder:**
![image](https://github.com/IntentArchitect/Support/assets/57346928/0865a87f-f57c-41cc-ad06-7a6f360761fd)

**Test App:**
![image](https://github.com/IntentArchitect/Support/assets/57346928/9912441d-9abf-4a0c-9513-25f42249a2e8)
![image](https://github.com/IntentArchitect/Support/assets/57346928/dd8e011d-e5ec-4be7-a2f3-59f9cefc3b1c)

**Other application:**
![image](https://github.com/IntentArchitect/Support/assets/57346928/c5f5bc87-99e8-4b68-ade2-b5ec4f267b9b)
![image](https://github.com/IntentArchitect/Support/assets/57346928/164276c8-ec52-4dd0-8680-5a3c78cf0220)

**Comment by dandrejvv** [comment]
Hi @Laura-BSC 

Did you set the following fields on the `Catalyst.Modules.RBAC` package?
![image](https://github.com/IntentArchitect/Support/assets/7236289/c7e288b0-6282-4231-94d8-3da717740d21)

You can find `Module Settings` by clicking on the `Catalyst.Modules.RBAC` package in your Module Builder:
![image](https://github.com/IntentArchitect/Support/assets/7236289/fbbe1be7-e82b-48ec-ba2f-de9dd4a12303)

Please try that and recompile and reinstall your module and see if the stereotypes show up in your other applications.
Hope this helps and let me know if this doesn't solve the problem.

**Comment by Laura-BSC** [comment]
Hi Dandre, 

I have set that on the module settings. I tried to install the module on one of our other projects and it works as expected, so I suspect there is an issue with the project i'm trying to install it to. I'll dig around and see if I can find the cause of the issue

**Comment by dandrejvv** [comment]
To confirm something else, could you verify that your RBAC module's `imodspec` file has a `metadata` section that resembles the following?

```xml
<metadata>
    <install target="Domain" src="../intent/TestModule/Intent.Metadata/Module Builder/Catalyst.Modules.RBAC/Catalyst.Modules.RBAC.pkg.config" externalReference="551ef154-873c-403c-b4a1-27a720dfeb84" />
</metadata>
```

**Comment by Laura-BSC** [comment]
It does.
 I played around a bit comparing the differences between the project that the RBAC module stereotypes worked in and the one that didn't. The noticeable difference is the one where it doesn't work makes use of another of our custom modules. It seems that when I install that module and the RBAC module, only the last one to be installed allows the stereotypes to be used. I have another custom module that doesn't cause this issue. I'll troubleshoot further and see if I can figure out what is causing the conflict between the two modules

**Comment by dandrejvv** [comment]
Hi @Laura-BSC . 
I see. If you do need one of us to assist in this matter let us know on the other support channel and we can have a call to investigate with you.

**Comment by Laura-BSC** [comment]
Hi Dandre,

I found the issue - some of the objects in the module builder had the same GUIDs. I must have copied things across from the other module as a starting point for the RBAC module or something and it kept the same Ids for the copied elements, so when I installed both modules, they were conflicting with one another

**Comment by dandrejvv** [comment]
Hi @Laura-BSC , I was about to provide that suggestion but it seems you beat me to it. I'm glad you managed to resolve your issue.
