### ISSUE TITLE
Intent.EntityFrameworkCore.Repositories.EFRepositoryInterface - Expose the "sync" version of `Any`

### ISSUE THREAD

**Issue by shainegordon** [IntentArchitect/Support#73]
### What problem are you trying to solve?

Somes it is easier to use the synchronous methods of EF Core e.g. inside a Fluent Validation `.Must` function.

`RepositoryBase` already has the `.Any` method, it just needs to be added to the interface, so that it is accessible on the domain-specific repositories

### Describe the solution you'd like

add the following line to `IEFRepository` - `bool Any(Expression<Func<TPersistence, bool>> filterExpression);`

**Comment by shainegordon** [comment]
Added PR https://github.com/IntentArchitect/Intent.Modules.NET/pull/8

**Comment by JonathanLydall** [comment]
Hi @shainegordon,

Many thanks for the PR, we can certainly add synchronous equivalents for all the current asynchronous operations, but just behind a an application setting.

Our of interest, why not use FluentValidation's `MustAsync` in this case?

**Comment by joelsteventurner** [comment]
Hi @shainegordon 
I have published a pre-release module which addresses this issue. If you install
Intent.EntityFrameworkCore.Repositories v4.2.10-pre.0

I have added a Database setting (see below) which when turned on adds synchronous versions of the repository methods to the repository.

![image](https://github.com/IntentArchitect/Support/assets/11704606/7c192943-c1cf-44b9-9207-720acda6b95d)
