### ISSUE TITLE
Bug/Feature: Application DB Context and Owned entities

### ISSUE THREAD

**Issue by shainegordon** [IntentArchitect/Support#78]
### What happened?

This is another where it's either a bug or a feature request.

If you have an owned entity, that entity won't appear on the `ApplicationDbContext`

Steps to reproduce:
* Create a fresh "Clean architecture" project.
* Execute software factory.
* On the domain model, create two classes, `Parent` and `Child`
* Create an association from `Parent` -> `Child`
* Make that an aggregate association: `Target End` `Is Collection` `true`, `Source End` `Is Navigable` `true`, `Is Collection` `false.

![image](https://github.com/IntentArchitect/Support/assets/1714867/5ba20290-736d-4e67-b127-399bd81d9123)

If you now run the software factory, you will see that only `Parent` gets added to `ApplicationDbContext` and `IApplicationDbContext`.

### What version of Intent Architect are you using?

4.0.6

### Additional information

I understand why this happens - Another entity owns the entity, so you should access it via the aggregate root/repository.
That is why NOT exposing a repository for `Child` 100% makes sense.

IMO, this rule should not apply to the `ApplicationDbContext`. 
There are cases, e.g. reporting, which I as a developer would like to be able to construct my own queries, regardless of the domain rules.

**Comment by joelsteventurner** [comment]
Hi @shainegordon 

I've added a ticket for our team to discuss this, I know we have a similar pattern in the repository space where you can opt into repositories for non-aggregates when required. 

Which approach do you think would be better to solve your requirement?
a) Adding all non-aggregate entities to the DBContext
b) white-listing non-aggregate entities to be added to the DBContext (through a stereotype)

**Comment by shainegordon** [comment]
I think this should be a module-level setting.

The "issue" I see with a stereotype, is that you can put this stereotype on a parent/single class, which doesn't really make sense.

**Comment by joelsteventurner** [comment]
This option would definitely be behind a module setting for backwards compatibility and we can definitely take a look some validations on the Stereotype for where it can be applied, my question was more around the idea that some aggregate roots can have deep hierarchies. 

In which case would you want all those children added to the DBContext?

**Comment by shainegordon** [comment]
I think every "table"/class should be on the db context

**Comment by joelsteventurner** [comment]
As per our discussion yesterday, after some investigation, you can apply the table stereo type to these domain entities which, will add the Entity to your DB Context. Note if you are dealing with compositional entities that they will no longer be set up with an "Has" rather than "Owns" an mapping.
