### ISSUE TITLE
Minimal hosting model - Multitenancy

### ISSUE THREAD

**Issue by shainegordon** [IntentArchitect/Support#82]
### What happened?

When you add multi-tenancy to an application with "Use minimal hosting model", the Program.cs file is modified incorrectly.

### Steps to reproduce:

- Create a new Clean Architecture application
- Include multitenancy
- Update all modules, include prerelease (Intent.Modules.AspNetCore.MultiTenancy 5.1.0-beta.3)
- Run the software factory.

See the images to see what happens

![image](https://github.com/IntentArchitect/Support/assets/1714867/5e0cd0bb-7583-4aa6-a4a3-559b01d7ed7f)
![image](https://github.com/IntentArchitect/Support/assets/1714867/be57203f-ed18-4848-a97b-d273b8806f35)

### What's expected:
`builder.Services.ConfigureMultiTenancy(builder.Configuration);` should be AFTER `var builder = WebApplication.CreateBuilder(args);`

`app.UseMultiTenancy();` should be AFTER `app.UseRouting();`

The module code in `development` looks correct, so something is afoot

### What version of Intent Architect are you using?

4.1.0.beta-16

**Comment by dandrejvv** [comment]
Good day @shainegordon. Thank you for raising this, we'll log this and have a look and get back to you. Apologies for the late reply.

**Comment by joelsteventurner** [comment]
Hi @shainegordon 

I have a pre-release fix out for this issue which you are welcome to try out.

Intent.Modules.AspNetCore.MultiTenancy v5.1.1-pre.2

Let me know if this resolves the issue.

**Comment by shainegordon** [comment]
> Hi @shainegordon
> 
> I have a pre-release fix out for this issue which you are welcome to try out.
> 
> Intent.Modules.AspNetCore.MultiTenancy v5.1.1-pre.2
> 
> Let me know if this resolves the issue.

Great, that seems to have done the trick
