### ISSUE TITLE
IntentIgnore is being ignored

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#84]
### What happened?

I've been using the intent ignore annotation for a while now, and it does work - but recently after updating my modules, it has been replaced with @IntentManageClass and then all my changes are ignored and wiped.

![image](https://github.com/IntentArchitect/Support/assets/129200997/d8ece238-cc5f-4c01-a903-1a5124510706)

A way for me to fix it for now is to edit the original file and save it - then it goes back to being ignored - the problem is - I have about 400 files that this happens to, which is very scary if I just miss one or don't do it with one file then all changes that previously made my code work suddenly is not there anymore.

### What version of Intent Architect are you using?

4

**Comment by dandrejvv** [comment]
Ticket update: We're still investigating the cause for this as it seems rather non-deterministic to reproduce.

**Comment by dandrejvv** [comment]
After some investigation, it seemed there was a stale module that was causing this misbehavior. After clearing the cache the problem seemed to have resolved itself.
