### ISSUE TITLE
IA Injects the ApiOKResponse decorator incorrectly after IA modules upgrade

### ISSUE THREAD

**Issue by nicodenysschen** [IntentArchitect/Support#87]
### What happened?

From what I can gather is that the correct solution may be:

`@ApiOkResponse({
  description: 'Result retrieved successfully.',
  type: [Number], // Use an array with the Number constructor
  isArray: true,    
})
`
because the function returns an array of numbers for example see screenshot as well:

`Promise<number[]>`

I can fix it manually but it keeps on replacing it, is there an Ignore I can use or do we require an upgraded module in IA?

![image](https://github.com/IntentArchitect/Support/assets/50710791/1335e5a5-bf26-4543-beb6-e964383f02c0)

### What version of Intent Architect are you using?

4.2.2

### Additional information

Latest NPM packages and Latest IA Modules

**Comment by joelsteventurner** [comment]
Hi @nicodenysschen 

I've logged a bug on our side to address the ApiOKResponse not correctly setting the isArray property, and will let you know when that is available. 

As an interim solution, as you suggest, you can use the code management systems to apply manual changes to the file.

Below is an example, applying the IntentIgnore to the class will stop Intent generating this code.

![image](https://github.com/IntentArchitect/Support/assets/11704606/b8dc9c8a-4cd9-453f-a913-5567e9d1af2a)

Let me know if you need further assistance around this.

**Comment by nicodenysschen** [comment]
Thank you I have implemented the [Number] and the @IntentIgnore() for now and it is a working work around.

**Comment by joelsteventurner** [comment]
Another option is to ignore the file in Intent Architect as illustrated below.

This will give you a similar effect, in that you will be able to edit file. The advantage to this approach in this is case, is that the software factory will remind you of this issue, and you can simply "un-ignore" the file once we release a patch for this.

On the other approach you'll need to remember to go remove the `IntentIgnore` when the patch is released.

![image](https://github.com/IntentArchitect/Support/assets/11704606/cca6419c-f3c0-49c5-a068-fca3c950e600)
