### ISSUE TITLE
Creating a custom command that takes a list of items

### ISSUE THREAD

**Issue by alinsky-afk** [IntentArchitect/Support#91]
### Ask a question

Hi All, 

Is it possible to create a custom command that accepts a list of items? For example I would like to mass insert records to a table and I would like pass a list as a parameter. Instead of looping through a list and making a single create request for each. I've attached a screenshot below for just an idea of what I want.

Thanks! 

 
![image](https://github.com/IntentArchitect/Support/assets/173789849/2296056c-4567-49b2-8ba7-968a5879d4b9)

**Comment by JonathanLydall** [comment]
Hi @alinsky-afk,

We don't presently have a mapping configuration which could be used to describe this requirement, but you can still model the command's contract and then implement the handler code manually.

For example, if you wanted to bulk create `Customers` as per the following:

![image](https://github.com/IntentArchitect/Support/assets/1290262/5554e7e9-a91b-4453-b9f6-7082f91a3b5e)

Create a _DTO_, with a name such as `CreateCustomerDto`, with the _Fields_ you need:

![image](https://github.com/IntentArchitect/Support/assets/1290262/317120cf-0962-4497-a82e-7c339eec4afc)

Then create a _Command_ with a name such as `CreateCustomersCommand`, add a `Customers` _Field_ to it set to `CreateCustomerDto` and ensure you have set _Is Collection_ for it:

![image](https://github.com/IntentArchitect/Support/assets/1290262/e1be702c-dc81-4afd-aa66-ebd73943f527)

Run the Software Factory and it will generate a stub for you, you can then just implement the logic you need in there:

![image](https://github.com/IntentArchitect/Support/assets/1290262/0c6d10d7-06c4-4a4a-b997-bdaf6633245a)

I've also logged a feature request for us possibly adding support for this kind of use case to our modules, however, as our resources are a bit limited at the moment, I can't say when we might be able to implement it.

Please don't hesitate to let me know if you have any additional comments or questions.

**Comment by alinsky-afk** [comment]
Thanks @JonathanLydall this worked just fine! 🔥
