### ISSUE TITLE
Is it possible to map/configure a CosmosDB container per reposition in a module?

### ISSUE THREAD

**Issue by swdvt** [IntentArchitect/Support#99]
### Ask a question

I would like to understand if its possible to have a CosmosDB container per repository in a module? I have two domain packages using CosmosDB provider it is possible to specify per domain package a CosmosDB container?

**Comment by joelsteventurner** [comment]
Hi @swdvt 

You can apply a `Container` stereotypes at various levels which will inform which container the documents are persisted to, for example.

In the image below I have the `Container` stereotype on the `Customer` configured to a `Customer` container. In this case the Customer document will go into the that container. I have the invoice configured to go to the Invoice container.

![image](https://github.com/user-attachments/assets/d39b959a-1383-4b98-a861-99bd788f9748)

While it's typical to have a container per document, you can also specify the container on the package itself or a folder which will cascade that container for all children who don't have a container specified.

Let me know if this answers the question or you need additional assistance.

**Comment by swdvt** [comment]
Thanks, that answers my question very nicely.
